# Numpy

Numpy is a general-purpose array processing package.It provides tools for working with multi-dimensional array objects.

### What is an array

An array is a data structure that stores values of same data type. In Python, this is the difference between arrays and lists. While lists can contain values corresponding to different data types; arrays can only contain values of same data type. Arrays are always created using square brackets[]


In [5]:
import numpy as np                   #import the numpy library (np is the alias name used for numpy)

In [4]:
arr=np.array([1,2,3,4,5])           #np.array is used to create an array, the array is always created starting with () & then[]

type(arr)

numpy.ndarray

In [5]:
arr.shape                          #this will always give the shape of the array (r,c)

(5,)

In [9]:
# Multidimensional Array

mul_arr=np.array([[1,2,3,4,5],
                  [6,7,8,9,10],
                  [11,12,13,14,15]])       #you can determine dimensions of array based on square brackets(this array is 2-D)

In [10]:
mul_arr.shape

(3, 5)

In [13]:
mul_arr.reshape(5,3)                   #you can reshape the array the way you want but the values inside cannot exceed r*c value

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [17]:
 # Accessng the array elements(Indeing)
    
arr=np.array([1,2,3,4,5])

In [18]:
arr[3]                              #you can access the elements using the index values

4

In [19]:
arr[3]=3                            #you can also update the elements usig the index values
print(arr)

[1 2 3 3 5]


In [38]:
mul_arr=np.array([[1,2,3,4,5],
                  [6,7,8,9,10],
                  [11,12,13,14,15]])

In [40]:
mul_arr[1:,2:]                   # in multidimensional the left is always row and right is always column(similar to slicing to access the elements)

array([[ 8,  9, 10],
       [13, 14, 15]])

In [41]:
mul_arr[1,0]=16                  # you can also update the element by directly accessing it
mul_arr

array([[ 1,  2,  3,  4,  5],
       [16,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [47]:
arr2=np.arange(0,10)          # arange func-used to generate array (start,stop,step_size) if step size not mentioned bydefault-1
print("arr2= ", arr2)

arr3=np.arange(0,20,2)       # here we gave stepsize as 2 
print("arr3= ", arr3)

arr2=  [0 1 2 3 4 5 6 7 8 9]
arr3=  [ 0  2  4  6  8 10 12 14 16 18]


In [48]:
np.linspace(start=1,stop=25,num=50)     #50 equally spaced points are created between 1 and 25

array([ 1.        ,  1.48979592,  1.97959184,  2.46938776,  2.95918367,
        3.44897959,  3.93877551,  4.42857143,  4.91836735,  5.40816327,
        5.89795918,  6.3877551 ,  6.87755102,  7.36734694,  7.85714286,
        8.34693878,  8.83673469,  9.32653061,  9.81632653, 10.30612245,
       10.79591837, 11.28571429, 11.7755102 , 12.26530612, 12.75510204,
       13.24489796, 13.73469388, 14.2244898 , 14.71428571, 15.20408163,
       15.69387755, 16.18367347, 16.67346939, 17.16326531, 17.65306122,
       18.14285714, 18.63265306, 19.12244898, 19.6122449 , 20.10204082,
       20.59183673, 21.08163265, 21.57142857, 22.06122449, 22.55102041,
       23.04081633, 23.53061224, 24.02040816, 24.51020408, 25.        ])

In [49]:
arr2[3:]=100              # this will update all elements from 3rd index to value 100 (this is also known as broadcasting)
arr2

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [51]:
arr2=arr3                 # both will have same values now

arr2[3:]=500 

arr2=  [ 0  2  4  6  8 10 12 14 16 18]
arr3=  [ 0  2  4  6  8 10 12 14 16 18]


In [53]:
arr2[3:]=500               # this will change the values in both arrays
arr2

array([  0,   2,   4, 500, 500, 500, 500, 500, 500, 500])

In [55]:
print("arr3= ", arr3)     # this happens because arrays in python are of reference type (to avoid this we use copy)

arr3=  [  0   2   4 500 500 500 500 500 500 500]


In [56]:
arr2=arr3.copy()          # to avoid the above problem we use copy function
arr2[3:]=1000

print("arr2= ", arr2)
print("arr3= ", arr3)

arr2=  [   0    2    4 1000 1000 1000 1000 1000 1000 1000]
arr3=  [  0   2   4 500 500 500 500 500 500 500]


In [58]:

new_arr=np.arange(1,10)
print(new_arr)
print(new_arr*2)               # will multiply all elements by 2
print(new_arr/2)               # will divide all elements by 2
print(new_arr>2)               # will return true if greater than 2 else will return false
print(new_arr[new_arr>2])      # will return all the elements greater than 2


[1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[False False  True  True  True  True  True  True  True]
[3 4 5 6 7 8 9]


In [60]:
abcd= np.arange(0,20).reshape(4,5)
abcd

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [61]:
np.ones(4,dtype=float)                 # will create array with all values as one

array([1., 1., 1., 1.])

In [63]:
np.ones((2,5),dtype=int)               # will create multidimensional array with all values as one

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [65]:
abc=np.random.rand(3,2)          # will create random values in the specified shape(all the random elemnets will be between 0&1)
print(abc)                       # this is based on random distribution 

[[0.06817241 0.4429101 ]
 [0.16885588 0.47178245]
 [0.270158   0.30731821]]


In [66]:
np.random.randn(2,2)             # same as above (but based on standard distribution)

array([[-0.12748445,  0.48538913],
       [ 0.4646119 ,  0.95683701]])

In [68]:
np.random.randint(0,100,8)       # in this 8 integers between 0-100 will be randomly chosen

array([21, 56,  1, 75, 55, 66, 79, 44])

In [71]:
np.random.randint(0,100,10).reshape(2,5)

array([[56, 67, 81, 96, 11],
       [29,  5, 65,  4, 42]])

In [74]:
np.random.random_sample((1,5))                # return random float values between 0-1 (here 1,5 is the shape provided)   

array([[0.84179948, 0.85888066, 0.53849397, 0.17281067, 0.32474171]])

In [10]:
a=np.array([[1,1],[1,2],
           [2,1],[2,2]], dtype=float)        # with help of dtype we can change the data type of an array
a.shape

(4, 2)

In [11]:
a.reshape(2,4)

array([[1., 1., 1., 2.],
       [2., 1., 2., 2.]])

In [9]:
a.ndim                                      # ndim function is used to know the dimension of array

2

In [15]:
b=np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [20]:
print("max= ",b.max())                   # to print maximum value in b
print("min= ",b.min())                   # to print minimum value in b
print("sum= ",b.sum())                   # returns the sum of the values in array
print("mean= ",b.mean())                 # returns mean(average) of the values in array
print("standard deviation= ",b.std())    # returns standard deviation of the values in array


max=  9
min=  1
sum=  25
mean=  5.0
standard deviation=  2.8284271247461903
